<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $products = [
            // Skincare Category Products
            [
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Organic Aloe Vera Gel',
                'description' => 'Pure natural aloe vera gel for skin hydration and healing. Rich in vitamins and minerals, this organic gel soothes irritated skin, reduces acne, and provides deep moisturization.',
                'short_description' => 'Pure natural aloe vera gel for skin hydration',
                'price' => 299,
                'compare_price' => 399,
                'sale_price' => 249,
                'sku' => 'ALOE-001',
                'barcode' => '9780001001001',
                'stock' => 120,
                'low_stock_threshold' => 20,
                'stock_status' => 'in_stock',
                'rating' => 4.5,
                'review_count' => 24,
                'sales_count' => 156,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Organic Aloe Vera Gel - Pure & Natural Skincare',
                'seo_description' => 'Shop pure organic aloe vera gel for hydration and healing. Natural skincare solution.',
            ],
            [
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Herbal Face Wash with Neem',
                'description' => 'Natural face wash formulated with neem and tulsi extract. Deep cleanses pores, removes impurities, and helps prevent acne. Suitable for all skin types, especially oily and acne-prone skin.',
                'short_description' => 'Natural face wash with neem and tulsi',
                'price' => 199,
                'compare_price' => 299,
                'sale_price' => 159,
                'sku' => 'FACE-002',
                'barcode' => '9780001002002',
                'stock' => 85,
                'low_stock_threshold' => 15,
                'stock_status' => 'in_stock',
                'rating' => 4.2,
                'review_count' => 18,
                'sales_count' => 234,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Herbal Face Wash - Neem & Tulsi Formula',
                'seo_description' => 'Natural herbal face wash with neem and tulsi for clear skin. Perfect for acne-prone skin.',
            ],
            [
                'category_id' => 1,
                'brand_id' => 1,
                'name' => 'Turmeric Face Mask',
                'description' => 'Golden turmeric face mask with natural ingredients. Reduces inflammation, brightens complexion, and provides anti-aging benefits. Mix with water for an effective skincare treatment.',
                'short_description' => 'Golden turmeric face mask for brightening',
                'price' => 349,
                'compare_price' => 449,
                'sale_price' => 299,
                'sku' => 'MASK-003',
                'barcode' => '9780001003003',
                'stock' => 60,
                'low_stock_threshold' => 10,
                'stock_status' => 'in_stock',
                'rating' => 4.7,
                'review_count' => 42,
                'sales_count' => 189,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Turmeric Face Mask - Natural Brightening Formula',
                'seo_description' => 'Premium turmeric face mask with natural ingredients for glowing skin.',
            ],

            // Hair Care Category Products
            [
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Herbal Hair Growth Oil',
                'description' => 'Premium herbal oil blend containing brahmi, bhringraj, and coconut oil. Promotes hair growth, reduces hair fall, and nourishes the scalp. Regular use results in stronger, healthier hair.',
                'short_description' => 'Herbal oil for hair growth and strength',
                'price' => 399,
                'compare_price' => 549,
                'sale_price' => 349,
                'sku' => 'OIL-004',
                'barcode' => '9780001004004',
                'stock' => 100,
                'low_stock_threshold' => 20,
                'stock_status' => 'in_stock',
                'rating' => 4.6,
                'review_count' => 67,
                'sales_count' => 312,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => false,
                'seo_title' => 'Herbal Hair Growth Oil - Brahmi & Bhringraj',
                'seo_description' => 'Premium herbal hair oil for growth and strength.',
            ],
            [
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Natural Shampoo Bar',
                'description' => 'Solid shampoo bar made with organic herbs and natural oils. Sulfate-free, eco-friendly, and long-lasting. Perfect for travelers and eco-conscious customers.',
                'short_description' => 'Eco-friendly natural shampoo bar',
                'price' => 249,
                'compare_price' => 349,
                'sale_price' => 199,
                'sku' => 'SHAMP-005',
                'barcode' => '9780001005005',
                'stock' => 75,
                'low_stock_threshold' => 15,
                'stock_status' => 'in_stock',
                'rating' => 4.4,
                'review_count' => 31,
                'sales_count' => 198,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Natural Shampoo Bar - Organic & Eco-Friendly',
                'seo_description' => 'Solid shampoo bar with natural herbs. Sulfate-free and long-lasting.',
            ],
            [
                'category_id' => 2,
                'brand_id' => 1,
                'name' => 'Anti-Dandruff Hair Treatment',
                'description' => 'Specialized treatment for dandruff and scalp conditions. Contains neem, tea tree, and coconut oil. Provides relief within 1-2 weeks of regular use.',
                'short_description' => 'Anti-dandruff treatment with neem',
                'price' => 299,
                'compare_price' => 399,
                'sale_price' => 249,
                'sku' => 'TREAT-006',
                'barcode' => '9780001006006',
                'stock' => 90,
                'low_stock_threshold' => 15,
                'stock_status' => 'in_stock',
                'rating' => 4.5,
                'review_count' => 54,
                'sales_count' => 267,
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => true,
                'seo_title' => 'Anti-Dandruff Hair Treatment - Neem & Tea Tree',
                'seo_description' => 'Effective anti-dandruff treatment for scalp health.',
            ],

            // Supplements Category Products
            [
                'category_id' => 3,
                'brand_id' => 1,
                'name' => 'Ashwagandha Capsules',
                'description' => 'Premium ashwagandha extract in capsule form. Helps reduce stress and anxiety, improves sleep quality, and boosts immunity. 500mg per capsule, 60 capsules per bottle.',
                'short_description' => 'Stress relief ashwagandha supplement',
                'price' => 499,
                'compare_price' => 699,
                'sale_price' => 399,
                'sku' => 'ASHW-007',
                'barcode' => '9780001007007',
                'stock' => 150,
                'low_stock_threshold' => 25,
                'stock_status' => 'in_stock',
                'rating' => 4.8,
                'review_count' => 89,
                'sales_count' => 456,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Ashwagandha Capsules - Natural Stress Relief',
                'seo_description' => 'Premium ashwagandha supplement for stress and anxiety relief.',
            ],
            [
                'category_id' => 3,
                'brand_id' => 1,
                'name' => 'Immune Booster Tablets',
                'description' => 'Comprehensive immune support formula with elderberry, echinacea, and vitamin C. Strengthens immunity naturally and helps prevent seasonal illnesses.',
                'short_description' => 'Natural immune support formula',
                'price' => 349,
                'compare_price' => 499,
                'sale_price' => 299,
                'sku' => 'IMMUN-008',
                'barcode' => '9780001008008',
                'stock' => 120,
                'low_stock_threshold' => 20,
                'stock_status' => 'in_stock',
                'rating' => 4.3,
                'review_count' => 38,
                'sales_count' => 201,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => false,
                'seo_title' => 'Immune Booster Tablets - Vitamin C & Elderberry',
                'seo_description' => 'Natural immune support with multiple health benefits.',
            ],
            [
                'category_id' => 3,
                'brand_id' => 1,
                'name' => 'Joint Support Capsules',
                'description' => 'Herbal formula for joint health and flexibility. Contains turmeric, ginger, and boswellia. Helps reduce joint pain and improve mobility.',
                'short_description' => 'Natural joint support supplement',
                'price' => 599,
                'compare_price' => 799,
                'sale_price' => 499,
                'sku' => 'JOINT-009',
                'barcode' => '9780001009009',
                'stock' => 80,
                'low_stock_threshold' => 15,
                'stock_status' => 'in_stock',
                'rating' => 4.6,
                'review_count' => 45,
                'sales_count' => 234,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => false,
                'seo_title' => 'Joint Support Capsules - Turmeric & Ginger',
                'seo_description' => 'Herbal joint support for mobility and flexibility.',
            ],

            // Ayurvedic Products
            [
                'category_id' => 4,
                'brand_id' => 1,
                'name' => 'Triphala Churna',
                'description' => 'Traditional Ayurvedic blend of three fruits for digestive health. Promotes regular digestion, detoxification, and overall wellness. Can be mixed with warm water.',
                'short_description' => 'Traditional Ayurvedic digestive blend',
                'price' => 199,
                'compare_price' => 299,
                'sale_price' => 149,
                'sku' => 'TRIP-010',
                'barcode' => '9780001010010',
                'stock' => 110,
                'low_stock_threshold' => 20,
                'stock_status' => 'in_stock',
                'rating' => 4.4,
                'review_count' => 52,
                'sales_count' => 289,
                'is_active' => true,
                'is_featured' => true,
                'is_trending' => true,
                'seo_title' => 'Triphala Churna - Ayurvedic Digestive Blend',
                'seo_description' => 'Traditional triphala powder for digestive health and detox.',
            ],
            [
                'category_id' => 4,
                'brand_id' => 1,
                'name' => 'Brahmi Vati Tablets',
                'description' => 'Ayurvedic brain tonic for improved memory and concentration. Contains brahmi, shankhpushpi, and other cognitive herbs. Perfect for students and professionals.',
                'short_description' => 'Brain tonic for memory and focus',
                'price' => 349,
                'compare_price' => 499,
                'sale_price' => 299,
                'sku' => 'BRAHM-011',
                'barcode' => '9780001011011',
                'stock' => 95,
                'low_stock_threshold' => 15,
                'stock_status' => 'in_stock',
                'rating' => 4.5,
                'review_count' => 36,
                'sales_count' => 178,
                'is_active' => true,
                'is_featured' => false,
                'is_trending' => false,
                'seo_title' => 'Brahmi Vati - Ayurvedic Brain Tonic',
                'seo_description' => 'Herbal brain tonic for memory and concentration.',
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}