<?php

namespace Database\Seeders;

use App\Models\Brand;
use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $brandId = Brand::where('slug', 'ipure-herbs')->value('id') ?? 1;
        $cat = fn(string $slug) => Category::where('slug', $slug)->value('id');

        $products = [
            // Weight Management
            ['category_id' => $cat('weight-management'), 'name' => 'SlimWell Protein Powder', 'slug' => 'slimwell-protein-powder', 'sku' => 'SLIM-PROT-500G', 'price' => 85.14, 'short_description' => 'Meal-replacement shake for healthy weight management and lean muscle tone.', 'description' => "Benefits:\n• Beneficial for weight management\n• Boosts immune system and metabolism\n• Healthy meal replacement shake for lean muscle tone\n• Contains Whey protein for muscle protein synthesis\n• Helps clean and detoxify the body\n\nHow to use: Replace one meal per day with SlimWell Shake. For best results, replace dinner daily.\n\nStorage: Close immediately after use. Consume within 20 days of opening.\n\nAvailable size: 500 gm", 'stock' => 50, 'is_featured' => true, 'is_trending' => true],
            ['category_id' => $cat('weight-management'), 'name' => 'SlimQem Capsules', 'slug' => 'slimqem-capsules', 'sku' => 'SLIMQEM-CAPS-60', 'price' => 70.46, 'short_description' => 'Natural capsules for weight management, metabolism boost and appetite suppression.', 'description' => "Benefits:\n1. Weight Management through appetite suppression\n2. Boosts Metabolism\n3. Lean Muscle Maintenance\n4. Detoxification with psyllium husk\n5. Immune Support\n6. Sustained Energy\n\nHow to Use: Take 2 capsules after meals.\n\nKey Ingredients: Whey Protein, Psyllium Husk, Vrikshamla (Garcinia Cambogia), Amalaki, Harada, Katuki.\n\nAvailable size: 60 Tabs", 'stock' => 100, 'is_featured' => true, 'is_trending' => false],

            // Bone & Joint Wellness
            ['category_id' => $cat('bone-joint-wellness'), 'name' => 'OrthoQem Oil', 'slug' => 'orthoqem-oil', 'sku' => 'ORTHOQ-OIL', 'price' => 62.52, 'short_description' => 'Herbal pain relief oil with 20+ Ayurvedic ingredients for joints and muscles.', 'description' => "Enriched with 20+ Ayurvedic ingredients, OrthoQem Oil offers effective pain relief without hot/cold burning sensation.\n\nBenefits:\n• Soothes joint and muscle pain\n• Skin-friendly, no irritation\n• Pleasant, relaxing aroma\n\nFor external use only. Avoid contact with eyes and open wounds.\n\nAvailable sizes: 100ml, 50ml", 'stock' => 80, 'is_featured' => false, 'is_trending' => false],
            ['category_id' => $cat('bone-joint-wellness'), 'name' => 'OrthoQem Tablet', 'slug' => 'orthoqem-tablet', 'sku' => 'ORTHOQ-TAB-60', 'price' => 70.69, 'short_description' => 'Herbo-mineral tablets for arthritis, spondylitis and joint pain.', 'description' => "Herbo-mineral combination for arthritic and joint pain management.\n\nBenefits:\n• Effective for spondylitis, backaches, and sprains\n• Reduces swelling of joints and muscles\n• Faster pain relief\n• Strengthens joints and muscles\n\nComposition (per tablet): Mahayograj guggul churna 150mg, Maharasnadi kwata churna 125mg, Nirgundi churna 125mg, Yavani 65mg, Shankha bhasma 65mg, Godanthi bhasma 65mg.\n\nFor best results: minimum three months.\n\nAvailable size: 60 Tabs", 'stock' => 60, 'is_featured' => false, 'is_trending' => false],
            ['category_id' => $cat('bone-joint-wellness'), 'name' => 'OrthoQem Gel', 'slug' => 'orthoqem-gel', 'sku' => 'ORTHOQ-GEL-30G', 'price' => 62.70, 'short_description' => 'Fast-acting herbal gel for muscle and joint pain — non-greasy and skin-friendly.', 'description' => "Fast-acting herbal formula for musculoskeletal pain relief.\n\nBenefits:\n• Potent Ayurvedic ingredients target pain and inflammation\n• Non-greasy, no residue\n• Rapid absorption for immediate relief\n• No burning or irritation\n\nUsage: Apply 2-3 times daily. Massage onto affected area until absorbed.\n\nAvailable size: 30gm", 'stock' => 70, 'is_featured' => false, 'is_trending' => false],

            // Respiratory Care
            ['category_id' => $cat('respiratory-care-immunity-booster'), 'name' => 'Breath Sure Ayurvedic Cough Kadha', 'slug' => 'breath-sure-cough-kadha', 'sku' => 'BREATHSURE-KADHA', 'price' => 63.12, 'short_description' => 'Non-drowsy Ayurvedic cough syrup for asthma, bronchitis, COPD, and immunity.', 'description' => "Indications: Asthma, Cough, COPD, Bronchitis, Allergies & Sinusitis, Common Cold.\n\nKey Benefits:\n• Supports healthy respiratory function\n• Non-drowsy, non-habit forming\n• Natural expectorant: clears mucus and phlegm\n• Bronchodilator properties\n• Immune boosting\n\nKey Ingredients: Thyme, Ivy (Bimbi), Camphor, Clove, Cardamom, Black Pepper, Ginger, Tulasi, Licorice.\n\nDosage: Adults: 10-15 ml + 20 ml lukewarm water twice daily. Children: 2.5-5 ml.\n\nAvailable sizes: 100 ml, 200 ml", 'stock' => 90, 'is_featured' => true, 'is_trending' => true],

            // Kidney Care
            ['category_id' => $cat('kidney-care'), 'name' => 'UroQem Syrup', 'slug' => 'uroqem-syrup', 'sku' => 'UROQEM-SYR-200ML', 'price' => 64.17, 'short_description' => 'Natural urinary alkalizer for UTI, burning micturition and kidney stone support.', 'description' => "Benefits:\n• Treats Urinary tract infections\n• Relieves burning micturition\n• Improves renal function\n• Helps with kidney stones\n• Activates complete Urinary system\n• Natural urinary alkalizer\n\nKey Ingredients: Shatavari, Kemua, Ajmod, Nirgundi, Mulethi, Jatamansi, Ashoka, Gokharu, Ashwagandha.\n\nAvailable size: 200 ml", 'stock' => 55, 'is_featured' => false, 'is_trending' => false],

            // Liver Care
            ['category_id' => $cat('liver-care-detoxification'), 'name' => 'LivoQem DS-32', 'slug' => 'livoqem-ds-32', 'sku' => 'LIVOQEM-DS32-60', 'price' => 67.34, 'short_description' => 'Hepatoprotective tablets for fatty liver, hepatitis, jaundice and liver detoxification.', 'description' => "Natural solution for liver health and detoxification.\n\nKey Benefits: Liver detoxification and repair, fatty liver and hepatitis support, reduces toxins, supports digestion, helps with jaundice and anemia.\n\nKey Ingredients (per tablet): Bhumi Amla 100mg, Bhringraj 75mg, Kutki 75mg, Giloy 50mg, Kalmegh 50mg, Makoy 50mg, Punarnava 50mg, Arjuna 25mg, Daru Haldi 25mg.\n\nDirections: 2 tablets morning and evening before meals.\n\nAvailable size: 60 Tablets", 'stock' => 65, 'is_featured' => false, 'is_trending' => false],
            ['category_id' => $cat('liver-care-detoxification'), 'name' => 'Live Amrit DS Syrup', 'slug' => 'live-amrit-ds-syrup', 'sku' => 'LIVEAMRIT-DS-200ML', 'price' => 63.88, 'short_description' => 'Polyherbal liver tonic for fatty liver, hepatitis, jaundice and liver detoxification.', 'description' => "Comprehensive liver health syrup.\n\nKey Benefits: Improves digestion, restores liver function, accelerates liver cell regeneration, protects from alcohol damage, supports convalescence.\n\nUseful in: NAFLD, Hepatitis, Jaundice, Liver Dysfunction, Cirrhosis.\n\nKey Ingredients: Milk Thistle, Kalmegh, Kutki, Punarnava, Bhringraj, Bhuiamla, Amla, Giloy, Makoi, Daruhaldi, Aloe vera.\n\nDosage: Children: ½ tsp twice daily. Adults: 2-3 tsp, 3-4 times daily.\n\nAvailable size: 200 ml", 'stock' => 75, 'is_featured' => false, 'is_trending' => false],

            // Heart Care
            ['category_id' => $cat('heart-care'), 'name' => 'CardioPro Syrup', 'slug' => 'cardiopro-syrup', 'sku' => 'CARDIOPRO-SYR-500ML', 'price' => 71.51, 'short_description' => '100% natural, sugar-free cardiac tonic for cholesterol, blood pressure and heart health.', 'description' => "Key Ingredients: Hawthorn, Grape Seed Extract, Kesar, Arjuna, Amla, Harad, Shatavari, Ashwagandha, Kaali Mirch, Jeera, Adrak, Pudina.\n\nKey Benefits: 100% natural and sugar-free, cardiac tonic, fights bad cholesterol (LDL), anti-inflammatory, supports blood circulation, prevents congestive heart failure. Helpful in Hypertension, Dyslipidemia, Coronary Heart Disease.\n\nDirections: 20-30 ml twice daily. Recommended treatment: 4-12 weeks.\n\nAvailable size: 500 ml", 'stock' => 40, 'is_featured' => true, 'is_trending' => false],

            // Diabetic Care
            ['category_id' => $cat('diabetic-care'), 'name' => 'DiboWell Protein Powder', 'slug' => 'dibowell-protein-powder', 'sku' => 'DIBOWELL-PROT-200G', 'price' => 69.41, 'short_description' => 'Complete nutrition for diabetics — supports blood sugar management and muscle health.', 'description' => "Complete nutrition for diabetics.\n\nAnti-Diabetic Blend: Banaba Extract, Guggle, Bitter Melon, Licorice, Cinnamon, Gurmar, Bilberry, Fenugreek.\n\nNutritional Blend: Whey Protein, Soya Oil, Maltodextrin, Dietary Fiber, DHA, Alpha Lipoic Acid, L-Carnitine, L-Taurine.\n\nKey Benefits: Healthy blood sugar, liver and kidney support, heart health, reduces cravings, prevents muscle loss.\n\nHow to Use: Add 10 gm (1 scoop) to 50 ml water. Use within 1 month of opening.\n\nAvailable size: 200 Gm", 'stock' => 45, 'is_featured' => false, 'is_trending' => false],
            ['category_id' => $cat('diabetic-care'), 'name' => 'DiboQem Tablet', 'slug' => 'diboqem-tablet', 'sku' => 'DIBOQEM-TAB-60', 'price' => 75.09, 'short_description' => 'Clinically proven herbal tablets to regulate glucose and improve insulin sensitivity.', 'description' => "Natural formulation for healthy glucose metabolism.\n\nKey Benefits: Regulates glucose metabolism, improves insulin sensitivity, boosts glycogen storage, balances cholesterol, protects liver, rejuvenates pancreatic B cells.\n\nKey Ingredients (per tablet): Swarnapatri 150mg, Madhunashini (Gymnema) 120mg, Saptachakra 120mg, Jambu 80mg, Karavallaka (Bitter Melon) 80mg, Haridra 80mg.\n\nHow to Use: 2 tablets twice daily after meals.\n\nAvailable size: 60 Tabs", 'stock' => 60, 'is_featured' => true, 'is_trending' => true],

            // Digestive Health
            ['category_id' => $cat('digestive-health-enhancer'), 'name' => 'LaxoQem Powder', 'slug' => 'laxoqem-powder', 'sku' => 'LAXOQEM-PWD-75G', 'price' => 63.77, 'short_description' => 'Ayurvedic constipation powder to regulate bowel movement and improve digestion.', 'description' => "100% natural constipation and indigestion remedy.\n\nBenefits: Relief from constipation, maintains healthy digestive system, stimulates secretion of digestive juices.\n\nIngredients: Isabgol, Sonamukhi, Harad, Amaltas, Mulethi, Saunf, Kala Namak.\n\nHow to Use: 1-2 teaspoons with lukewarm water before bedtime.\n\nAvailable size: 75 gm", 'stock' => 85, 'is_featured' => false, 'is_trending' => false],
            ['category_id' => $cat('digestive-health-enhancer'), 'name' => 'Digo-Amrit Syrup', 'slug' => 'digo-amrit-syrup', 'sku' => 'DIGOAMRIT-SYR-200ML', 'price' => 63.88, 'short_description' => 'Natural digestive syrup for indigestion, acidity, gas, bloating, GERD and constipation.', 'description' => "Natural solution for digestive complaints.\n\nKey Benefits: Activates digestive system, neutralizes gastric acid, relieves gas and flatulence, alleviates heartburn and GERD, improves enzyme secretion, stimulates appetite.\n\nKey Ingredients: Papaya, Guava, Triphala, Bael Fruit, Dalchini, Pudina, Ginger, Black Pepper, Pippali, Jeera, Haritaki.\n\nDosage: Children: ½ tsp twice daily. Adults: 2-3 tsp, 3-4 times daily.\n\nAvailable size: 200 ml", 'stock' => 70, 'is_featured' => false, 'is_trending' => false],

            // Women's Health
            ['category_id' => $cat('womens-health-enhancer'), 'name' => 'GyNo-Cyst Tablets', 'slug' => 'gyno-cyst-tablets', 'sku' => 'GYNOCYST-TAB-30', 'price' => 73.61, 'short_description' => 'Non-hormonal dietary supplement for PCOS/PCOD management and hormonal balance.', 'description' => "Non-hormonal PCOS/PCOD management supplement.\n\nBenefits: Natural solution for ovulation and implantation, enhances insulin response, maintains hormonal balance, supports female reproductive health.\n\nKey Ingredients (per tablet): Myo-inositol 1000mg, Fenumannan® (Fenugreek Extract 60% Galactomannan) 100mg, L-methylfolate Calcium 100mcg, Vitamin D3 1000 IU.\n\nDirection of Use: One capsule daily.\n\nAvailable size: 30 Tablets", 'stock' => 50, 'is_featured' => true, 'is_trending' => true],
            ['category_id' => $cat('womens-health-enhancer'), 'name' => 'GynoSure Syrup', 'slug' => 'gynosure-syrup', 'sku' => 'GYNOSURE-SYR', 'price' => 64.40, 'short_description' => 'Polyherbal non-hormonal syrup for menstrual irregularities, PCOS, and female infertility.', 'description' => "Polyherbal, non-hormonal Ayurvedic remedy for female health.\n\nBenefits: Enhances endometrial health, normalizes menstrual blood flow, supports oligomenorrhea, DUB, metrorrhagia treatment, helps with PCOS, leucorrhea, uterine spasms.\n\nDirection of Use: 15-20 ml with water twice daily, an hour after meals. Minimum 3 months. Discontinue during menstruation.\n\nAvailable sizes: 200 ml, 470 ml", 'stock' => 55, 'is_featured' => true, 'is_trending' => false],

            // Men's Health
            ['category_id' => $cat('mens-health-enhancer'), 'name' => 'Shilajit Gold Resin', 'slug' => 'shilajit-gold-resin', 'sku' => 'SHILAJIT-GOLD-RESIN', 'price' => 95.62, 'short_description' => '100% pure Himalayan Shilajit resin with Ashwagandha and Swarna Bhasma for strength and vitality.', 'description' => "100% Pure Himalayan Shilajit with Swarna Bhasma.\n\nHealth Benefits: Boosts immunity, enhances strength and stamina, slows aging, reduces stress, boosts libido, strengthens bones and muscles.\n\nKey Ingredients (per 1g): Shilajit 350mg, Ashwagandha Extract 150mg, Coffee Extract 150mg, Gokshura Extract 100mg, Haldi Extract 50mg, Kali Musli Extract 50mg, Elaichi Oil 10mg, Swarna Bhasma 0.50mg.\n\nFeatures: High Fulvic Acid, 80+ Micronutrients, Clinically Tested for Heavy Metals.", 'stock' => 30, 'is_featured' => true, 'is_trending' => true],
        ];

        foreach ($products as $data) {
            Product::updateOrCreate(['slug' => $data['slug']], array_merge($data, [
                'brand_id'  => $brandId,
                'rating'    => 4.5,
                'is_active' => true,
            ]));
        }
    }
}
